#include "libros.h"

Libro LIBROS[] = {
        {"Cell", "Horror", 2006},
        {"The Street Lawyer", "Thriller", 1998},
        {"Nineteen Minutes", "Thriller", 2007},
        {"Harry Potter y la piedra filosofal", "Fantasy", 1997},
        {"Armageddon", "Post-apocalyptic fiction", 2003},
        {"The Jester", "Historical fiction", 2003},
        {"Harry Potter y el prisionero de Azkaban", "Fantasy", 1999},
        {"Star Wars: Episode I The Phantom Menace", "Science fiction", 1999},
        {"Dreamcatcher", "Fantasy", 2001},
        {"Rainbow Six", "Thriller", 1998},
        {"Hannibal", "Horror", 1999},
        {"Twelve Sharp", "Crime", 2006},
        {"The Bear and the Dragon", "Thriller", 2000},
        {"The Testament", "Adventure Story", 1999},
        {"Red Rabbit", "Historical fiction", 2002},
        {"Anansi Boys", "Fantasy", 2005},
        {"Airframe", "Thriller", 1997},
        {"Harry Potter y la camara secreta", "Fantasy", 1998},
        {"The King of Torts", "Thriller", 2003},
        {"The Da Vinci Code", "Mystery", 2003},
        {"Harry Potter y la Orden del Fenix", "Fantasy", 2003},
        {"Mary, Mary", "Crime", 2005},
        {"The Summons", "Thriller", 2002},
        {"Bag of Bones", "Horror", 1998},
        {"The 5th Horseman", "Thriller", 2006},
        {"Step on a Crack", "Thriller", 2007},
        {"Winter's Heart", "Fantasy", 2000},
        {"Plum Island", "Fiction", 1997},
        {"Eleven on Top", "Crime", 2005},
        {"Harry Potter y el misterio del principe", "Fantasy", 2005},
        {"The Closers", "Crime", 2005},
        {"Glorious Appearing", "Post-apocalyptic fiction", 2004},
        {"Prey ", "Science fiction", 2002},
        {"The Last Juror", "Thriller", 2004},
        {"'S' Is for Silence", "Mystery", 2005},
        {"4th of July", "Mystery", 2005},
        {"Harry Potter y las reliquias de la Muerte", "Fantasy", 2007},
        {"The Shelters of Stone", "Historical fiction", 2002},
        {"Harry Potter y el caliz de fuego", "Fantasy", 2000},
        {"The Dark Tower VII: The Dark Tower", "Fantasy", 2004},
        {"Book of the Dead ", "Crime", 2007},
        {"The Dark Tower VI: Song of Susannah", "Fantasy", 2004},
        {"Cold Mountain", "Historical novel", 1997},
        {"A Feast for Crows", "Fantasy", 2005}
};

size_t LONGITUD_LIBROS = sizeof(LIBROS) / sizeof(Libro);
